Create View VW_COG_MAXLOGON
(
CAMID,
LASTLOGONTIME,
USERNAME,
SECURITY_CONTAINER
)
AS
SELECT  DISTINCT(S1.COGIPF_CAMID) CAMID,
        TRUNC(S1.COGIPF_LOCALTIMESTAMP) LASTLOGONTIME,
        S1.COGIPF_USERNAME USERNAME,
        
       ( CASE
            WHEN S1.COGIPF_CAMID LIKE '%Series 7%' THEN 'Series 7'
            WHEN S1.COGIPF_CAMID LIKE '%LDS%' THEN 'ADLDS'
        END) Security_Container    
FROM    COGIPF_USERLOGON S1
INNER JOIN
(
SELECT  MAX(COGIPF_LOCALTIMESTAMP) COGIPF_LOCALTIMESTAMP,
        COGIPF_CAMID
FROM    COGIPF_USERLOGON
WHERE   COGIPF_LOGON_OPERATION = 'Logon'           
        AND
        COGIPF_USERNAME != 'not available'
GROUP BY
        COGIPF_CAMID
) S2
ON  S1.COGIPF_CAMID = S2.COGIPF_CAMID
AND
    TRUNC(S1.COGIPF_LOCALTIMESTAMP) = TRUNC(S2.COGIPF_LOCALTIMESTAMP)
GROUP BY
    S1.COGIPF_USERNAME,
    S1.COGIPF_LOCALTIMESTAMP,
    S1.COGIPF_CAMID
ORDER BY TRUNC(S1.COGIPF_LOCALTIMESTAMP) DESC

COMMIT
