DROP VIEW VW_COGREMOTEACCESS;

/* Formatted on 11/03/2015 8:41:18 AM (QP5 v5.269.14213.34769) */
CREATE OR REPLACE FORCE VIEW VW_COG_REMOTEACCESS
(
   DISPATCHER,
   COGIPF_SESSIONID,
   COGIPF_USERNAME,
   COGIPF_THREADID,
   STATUS,
   COGIPF_LOCALTIMESTAMP,
   COGIPF_TARGET_TYPE,
   COGIPF_TARGET_PATH
)
AS
     SELECT /*+ INDEX(COGIPF_USERLOGON) */
           CASE COGIPF_USERLOGON.COGIPF_HOST_IPADDR
               WHEN '<IP>' THEN 'Disp1'
               WHEN '<IP>' THEN 'Disp2'
               WHEN '<IP>' THEN 'Disp3'
               ELSE 'OTHER'
            END
               DISPATCHER,
            COGIPF_USERLOGON.COGIPF_SESSIONID,
            COGIPF_USERLOGON.COGIPF_USERNAME,
            COGIPF_USERLOGON.COGIPF_THREADID,
            COGIPF_USERLOGON.COGIPF_STATUS Status,
            COGIPF_ACTION.COGIPF_LOCALTIMESTAMP,
            COGIPF_ACTION.COGIPF_TARGET_TYPE,
            COGIPF_ACTION.COGIPF_TARGET_PATH
       FROM COGIPF_USERLOGON, COGIPF_ACTION
      WHERE     COGIPF_USERLOGON.COGIPF_SESSIONID =
                   COGIPF_ACTION.COGIPF_SESSIONID(+)
            AND COGIPF_USERLOGON.COGIPF_USERNAME =
                   USERENV ('client_info') || SUBSTR (UID, 1, 0)
            AND COGIPF_ACTION.COGIPF_TARGET_TYPE IN ('PACKAGE',
                                                     'DATASOURCECONNECTION')
            AND COGIPF_USERLOGON.COGIPF_THREADID LIKE 'http-%'
            AND TO_CHAR (COGIPF_USERLOGON.COGIPF_LOCALTIMESTAMP, 'DD/MM/YYYY') =
                   TO_CHAR (CURRENT_DATE, 'DD/MM/YYYY')
   ORDER BY COGIPF_USERLOGON.COGIPF_LOCALTIMESTAMP DESC;
