CREATE VIEW VW_CM_OBJECT_OWNERS
(
CMID
,OBJNAME
,CMID_MREFNOORD2
,REFCMID
,CMID_CMOBJNAMES_BASE
,LOCALEID
,MAPDLOCALEID
,NAME_CMOBJNAMES_BASE
,ISDEFAULT
,CMID_CMOBJECTS
,PCMID
,OBJVERSION
,CREATED
,MODIFIED
,DISABLED
,CLASSID
)
AS
/* Formatted on 16/12/2015 1:50:02 PM (QP5 v5.287) */
SELECT /*+ INDEX(CMOBJPROPS33) */ CMOBJPROPS33.CMID AS CMID, 
       CMOBJPROPS33.NAME AS OBJNAME, 
       CMREFNOORD2.CMID AS CMID_MREFNOORD2, 
       CMREFNOORD2.REFCMID AS REFCMID, 
       CMOBJNAMES_BASE.CMID AS CMID_CMOBJNAMES_BASE, 
       CMOBJNAMES_BASE.LOCALEID AS LOCALEID, 
       CMOBJNAMES_BASE.MAPDLOCALEID AS MAPDLOCALEID, 
       CMOBJNAMES_BASE.NAME AS NAME_CMOBJNAMES_BASE, 
       CMOBJNAMES_BASE.ISDEFAULT AS ISDEFAULT, 
       CMOBJECTS.CMID AS CMID_CMOBJECTS, 
       CMOBJECTS.PCMID AS PCMID, 
       CMOBJECTS.VERSION AS OBJVERSION, 
       CMOBJECTS.CREATED AS CREATED, 
       CMOBJECTS.MODIFIED AS MODIFIED, 
       CMOBJECTS.DISABLED AS DISABLED, 
       CMOBJECTS.CLASSID AS CLASSID 
  FROM PRODCOGNOS10_CS.CMOBJPROPS33 CMOBJPROPS33 
       INNER JOIN PRODCOGNOS10_CS.CMREFNOORD2 CMREFNOORD2 
          ON CMOBJPROPS33.CMID = CMREFNOORD2.REFCMID 
       RIGHT JOIN PRODCOGNOS10_CS.CMOBJNAMES_BASE CMOBJNAMES_BASE 
          ON CMREFNOORD2.CMID = CMOBJNAMES_BASE.CMID, 
       PRODCOGNOS10_CS.CMOBJECTS CMOBJECTS 
 WHERE CMOBJNAMES_BASE.ISDEFAULT = 1 + UID * 0 
   AND CMOBJNAMES_BASE.CMID = CMOBJECTS.CMID 
 ORDER BY CMOBJPROPS33.CMID  
