DROP VIEW VW_CM_CMID_CONTTREE;

/* Formatted on 8/02/2016 1:20:56 PM (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW VW_CM_CMID_CONTTREE
(
   LINENUM,
   CMID,
   PCMID,
   TREE,
   Version,
   LOCALEID,
   MAPDLOCALEID
)
AS
/* Formatted on 9/02/2016 6:51:06 AM (QP5 v5.287) */
    SELECT /*+ INDEX(CMOBJNAMES_BASE) */ ROWNUM, 
       CMOBJECTS.cmid, 
       CMOBJECTS.pcmid, 
       SYS_CONNECT_BY_PATH('Name: ' || CMOBJNAMES_BASE.name || ', CMID: ' || CMOBJECTS.cmid, ' -> ') tree, 
       Version, 
       LOCALEID, 
       MAPDLOCALEID 
  FROM prodcognos10_CS.CMOBJECTS, 
       prodcognos10_CS.CMOBJNAMES_BASE 
 WHERE CMOBJECTS.pcmid = CMOBJNAMES_BASE.cmid 
   AND CMOBJECTS.CLASSID = 10 
   AND CMOBJNAMES_BASE.ISDEFAULT = 1 
   AND CMOBJNAMES_BASE.LOCALEID = 98 
CONNECT BY PRIOR NULLIF(CMOBJECTS.cmid, CMOBJECTS.pcmid) = CMOBJECTS.pcmid 
       AND CMOBJNAMES_BASE.ISDEFAULT = 1 
       AND CMOBJNAMES_BASE.LOCALEID = 98
