DROP VIEW VW_CM_PORTLETS_OWNER;

CREATE VIEW VW_CM_PORTLETS_OWNER
(
CMID
,OBJECTNAME
,PROPID
,CMID_CMREFORD1
,ORD
,REFCMID
,CMID_CMOBJNAMES_BASE
,LOCALEID
,MAPDLOCALEID
,NAME_CMOBJNAMES_BASE
,ISDEFAULT
,CMID_CMOBJECTS
,PCMID
,OBJVERSION
,CREATED
,MODIFIED
,CLASSID
)
AS
SELECT /*+ USE_NL(CMOBJECTS,CMOBJNAMES_BASE,CMREFORD1) */ CMOBJPROPS33.CMID AS CMID, 
       CMOBJPROPS33.NAME AS OBJECTNAME, 
       CMREFORD1.PROPID AS PROPID, 
       CMREFORD1.CMID AS CMID_CMREFORD1, 
       CMREFORD1.ORD AS ORD, 
       CMREFORD1.REFCMID AS REFCMID, 
       CMOBJNAMES_BASE.CMID AS CMID_CMOBJNAMES_BASE, 
       CMOBJNAMES_BASE.LOCALEID AS LOCALEID, 
       CMOBJNAMES_BASE.MAPDLOCALEID AS MAPDLOCALEID, 
       CMOBJNAMES_BASE.NAME AS NAME_CMOBJNAMES_BASE, 
       CMOBJNAMES_BASE.ISDEFAULT AS ISDEFAULT, 
       CMOBJECTS.CMID AS CMID_CMOBJECTS, 
       CMOBJECTS.PCMID AS PCMID, 
       CMOBJECTS.VERSION AS OBJVERSION, 
       CMOBJECTS.CREATED AS CREATED, 
       CMOBJECTS.MODIFIED AS MODIFIED, 
       CMOBJECTS.CLASSID AS CLASSID 
  FROM PRODCOGNOS10_CS.CMOBJPROPS33 CMOBJPROPS33 
       RIGHT JOIN PRODCOGNOS10_CS.CMREFORD1 CMREFORD1 
          ON CMOBJPROPS33.CMID = CMREFORD1.CMID + 0, 
       PRODCOGNOS10_CS.CMOBJNAMES_BASE CMOBJNAMES_BASE, 
       PRODCOGNOS10_CS.CMOBJECTS CMOBJECTS 
 WHERE CMOBJECTS.CMID = CMOBJNAMES_BASE.CMID + 0 
   AND CMOBJNAMES_BASE.CMID = CMREFORD1.REFCMID + 0 
   AND CMOBJNAMES_BASE.ISDEFAULT = 1 
   AND CMOBJPROPS33.NAME IS NOT NULL 
   AND CMOBJNAMES_BASE.LOCALEID BETWEEN 96 AND 98 
 ORDER BY CMOBJPROPS33.CMID
