/****** Script for SelectTopNRows command from SSMS  ******/
SELECT * FROM [INCIDENTS_ALTERS]
 WHERE [FEED_NAME] = 'HAIL'
 ORDER BY [STARTDATETIME] DESC

SELECT MAX(CAST([OBJECTID] AS DECIMAL(6,0))) AS OBJECTID
  FROM [INCIDENTS_ALTERS]
  WHERE [FEED_NAME] = 'HAIL'
  
SELECT *
  FROM [INCIDENTS_ALTERS]
FULL OUTER JOIN [INCIDENTS_HAIL]
ON [INCIDENTS_ALTERS].[GEOEVENTID] = [INCIDENTS_HAIL].[GID] 
WHERE [INCIDENTS_ALTERS].[FEED_NAME] = 'Hail'
AND [INCIDENTS_HAIL].[HAILPROBABILITY] = 90 AND VIL > 50
ORDER BY [INCIDENTS_ALTERS].[STARTDATETIME] DESC

exec sp_configure 'Ad Hoc Distributed Queries', 1;
GO
RECONFIGURE;
GO

DECLARE @S varchar(max),
        @Split char(1),
        @X xml,
		@GID varchar(10),
		@filepath varchar(max),
		@sql as varchar(max)

SET @S = ' '
SET @X = ' '
SET @GID = ' '

select @S = [IMPACTED_POSTCODES] , @Split = ',' from 
(
SELECT [IMPACTED_POSTCODES]
  FROM [INCIDENTS_ALTERS]
  
FULL OUTER JOIN [INCIDENTS_HAIL]

ON [INCIDENTS_ALTERS].[GEOEVENTID] = [INCIDENTS_HAIL].[GID] 
WHERE [INCIDENTS_ALTERS].[FEED_NAME] = 'Hail'
AND [INCIDENTS_HAIL].[HAILPROBABILITY] = 90 AND VIL > 50 
) AS ROW

select @S;
SELECT @X = CONVERT(xml,' <root> <s>' + REPLACE(@S,@Split,'</s> <s>') + '</s>   </root> ');
select @X;

SELECT [impacted_postcode] = T.c.value('.','varchar(20)') 
INTO #TempTbl
FROM @X.nodes('/root/s') T(c)

Select @GID = [GID]
from [INCIDENTS_HAIL]
WHERE [INCIDENTS_HAIL].[HAILPROBABILITY] = 90 AND VIL > 50 

Select @GID

SET @filepath = 'C:\Cognos_BiSysMon\audit\esri\test\' +@GID+ '.xlsx'
Select @filepath

/**RBI ALL Policies ***/ 
SET @sql = '
insert into OPENROWSET(''Microsoft.Jet.OLEDB.4.0'',
''Excel 8.0;Database='' + @filename + '';'',''SELECT * FROM [SheetName$]'')
SELECT * FROM #TempTbl
LEFT OUTER JOIN [RIF_HMY]
ON #TempTbl.impacted_postcode = [RIF_HMY].[POSTAL_POST_CODE]
'
Exec (@sql)

INSERT INTO OPENROWSET('Microsoft.ACE.OLEDB.12.0',
'Text;Database=C:\Cognos_BiSysMon\audit\esri\test\;HDR=YES;FMT=Delimited','SELECT * FROM [R_@GID.csv]')
SELECT * FROM #TempTbl
LEFT OUTER JOIN [RIF_HMY]
ON #TempTbl.impacted_postcode = [RIF_HMY].[POSTAL_POST_CODE]


/**WFI ALL Policies ***/ 
SELECT * FROM #TempTbl
LEFT OUTER JOIN 
(
	SELECT [PolicyID],[producttype],[AreaManager],[StateSummary],[Town],[Suburb],[POSTCODE_CODE],[Address_Line1],[Address_Line2]
	FROM [ALL_IFC_HMY]
) RBI
ON #TempTbl.impacted_postcode = RBI.[POSTCODE_CODE]

/**CGU ALL Policies ***/ 
SELECT * FROM #TempTbl
LEFT OUTER JOIN [Property_aus_HMY]
ON #TempTbl.impacted_postcode = [Property_aus_HMY].[postcodeSummary]

/**DI ALL Policies ***/ 
SELECT * FROM #TempTbl
LEFT OUTER JOIN 
(
	Select [POLICYNO],[PRODUCT],[INSURED_GIVENNAME1],[INSURED_SURNAME1],
  [INSURED_MOBPHONE_AREACODE1],[INSURED_MOBEPHONENO1],[INSURED_EMAIL1],[STATE_KEPT],[TOWN_KEPT],[POSTCODE_KEPT]
	FROM [BOAT_FREQ_MAPPING]
	UNION
	Select [POLICYNO],[PRODUCT],[INSURED_GIVENNAME1],[INSURED_SURNAME1],
  [INSURED_MOBPHONE_AREACODE1],[INSURED_MOBEPHONENO1],[INSURED_EMAIL1],[STATE_KEPT],[TOWN_KEPT],[POSTCODE_KEPT]
	FROM [CAR_FREQ_MAPPING]
	UNION
	Select [POLICYNO],[PRODUCT],[INSURED_GIVENNAME1],[INSURED_SURNAME1],
  [INSURED_MOBPHONE_AREACODE1],[INSURED_MOBEPHONENO1],[INSURED_EMAIL1],[STATE_KEPT],[TOWN_KEPT],[POSTCODE_KEPT] 
	FROM [CVAN_FREQ_MAPPING]
	UNION
	Select [POLICYNO],[PRODUCT],[INSURED_GIVENNAME1],[INSURED_SURNAME1],
  [INSURED_MOBPHONE_AREACODE1],[INSURED_MOBEPHONENO1],[INSURED_EMAIL1],[STATE_KEPT],[TOWN_KEPT],[POSTCODE_KEPT] 
	FROM [HOME_FREQ_MAPPING]
	UNION
	Select [POLICYNO],[PRODUCT],[INSURED_GIVENNAME1],[INSURED_SURNAME1],
  [INSURED_MOBPHONE_AREACODE1],[INSURED_MOBEPHONENO1],[INSURED_EMAIL1],[STATE_KEPT],[TOWN_KEPT],[POSTCODE_KEPT] 
	FROM [PDV_FREQ_MAPPING]
) DI
ON
	#TempTbl.impacted_postcode = DI.[POSTCODE_KEPT]

DROP TABLE #TempTbl  

